### ISSUE TITLE
Is there any PC emulator than can Emulate a DC keyboard?

### ISSUE THREAD

**Issue by RetroGameTalk** [DerekPascarella/NeonGenesisEvangelionTypingProjectE-EnglishPatchDreamcast#1]
Seems like a PC keyboard > DC Keyboard shouldn't be too hard to replicate.
But is there an emulator that supports DC keyboards emulation?

**Comment by DerekPascarella** [comment]
I did testing of this patch in Demul during development before testing on original hardware.  Demul allows for the use of your computer's keyboard as if it were a standard Dreamcast keyboard.

**Comment by RetroGameTalk** [comment]
Thanks got it to work.
